slovo/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("",views.home, name="home"),
    path('signup/',views.signup, name='signup'),
    path('logout/',views.logout_view, name='logout'),
    path('login/',views.login_user, name='login'),
    path('settings/',views.settings,name="settings"),
    path('delete/',views.delete_account,name="delete"),
    path('terms_of_use/',views.terms_of_use, name="terms_of_use"),
    path('about/',views.about, name="about"),
    path('privacy/',views.privacy, name="privacy"),
    path('contact/',views.contact, name="contact"),
]

slovo/slovo/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("",include("core.urls")),
    path("",include("prom_exporter.urls")),
    path("translate/",include("translation.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

slovo/translation/urls.py
from django.urls import path
from . import views 
from translation.Translation import Translation
from django.contrib.auth.decorators import login_required
app_name = 'translation'

urlpatterns = [
    # path("",views.translate, name="translate"),
    path("",login_required(Translation.as_view(),login_url='/login'), name="translate"),
    path("profil/",views.profil,name="profil"),
]

slovo/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
        

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': ' repeat password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

class UpdateUserForm(forms.Form):

    class Meta:
       fields = ('username','email')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
class PasswordForm(forms.Form):
    class Meta:
        fields = ('former_pwd','new_pwd','confirm_pwd')
    former_pwd = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))  
    new_pwd = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    confirm_pwd = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': ' repeat password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

slovo/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse
from .forms import SignupForm, UpdateUserForm, PasswordForm, LoginForm
from .utils import get_client_browser, get_client_ip
import logging
from datetime import datetime
from django.contrib.auth.models import User 
from prom_exporter.views import COUNT_REQ, COUNT_HOME, COUNT_LOGOUT, COUNT_SIGNUP
from django.contrib.auth import authenticate, login

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

@require_http_methods(["GET"])
def about(request):
    return render(request,"core/about.html")

@require_http_methods(["GET"])
def contact(request):
    return render(request,"core/contact.html")

@require_http_methods(["GET"])
def privacy(request):
    return render(request,"core/privacy.html")

@require_http_methods(["GET"])
def terms_of_use(request):
    return render(request,"core/terms_of_use.html")

@require_http_methods(["GET"])
def home(request:WSGIRequest)->HttpResponse:
    COUNT_REQ.inc()
    COUNT_HOME.inc()
    logger.info(f"{request.method} {request.get_full_path()} ; IP_CLIENT : {get_client_ip(request)} ; HTTP_SEC_CH_UA : { get_client_browser(request)}")
    return render(request,"core/home.html")

@csrf_protect
def signup(request:WSGIRequest)->HttpResponse:
    COUNT_REQ.inc()
    COUNT_SIGNUP.inc()
    logger.info(f"{request.method} {request.get_full_path()} ; IP_CLIENT : {get_client_ip(request)} ; HTTP_SEC_CH_UA : { get_client_browser(request)}")
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info(f"[{datetime.now().strftime('%H:%M:%S')}] New User saved")
            return redirect('/login/')
        else:
            logger.info(f"[{datetime.now().strftime('%H:%M:%S')}] Invalid Form")
    else:
        form = SignupForm()

    return render(request, 'core/signup.html',{
        'form':form 
    })

@csrf_protect
@login_required
def logout_view(request:WSGIRequest)->HttpResponse:
    COUNT_REQ.inc()
    COUNT_LOGOUT.inc()
    logger.info(f"{request.method} {request.get_full_path()} ; IP_CLIENT : {get_client_ip(request)} ; HTTP_SEC_CH_UA : { get_client_browser(request)}")
    logout(request)
    logger.info(f"[{datetime.now().strftime('%H:%M:%S')}] User succesfully logged out")
    return redirect('/')

def credentials_taken(username:str,email:str,user_pk:int)->bool:
    """
    Check if the credentials already exists in base 
    """
    if User.objects.exclude(pk=user_pk).filter(username=username).exists() or  User.objects.exclude(pk=user_pk).filter(email=email).exists() :

        return True 
    return False 
@login_required
def settings(request:WSGIRequest)->HttpResponse:
    user = request.user
    message = False
    if request.method == 'POST':
        if 'email_username' in request.POST:
            form = UpdateUserForm(request.POST)
            if form.is_valid():
                new_username = form.cleaned_data['username']
                new_email = form.cleaned_data["email"]
                if not credentials_taken(new_username,new_email,user.id) :
   
                    user.username = new_username
                    user.email = new_email
                    user.save()
                    return redirect('/logout')
                else : 
                    message = "Credentials are already taken "
        elif 'password' in request.POST : 
            form_pwd = PasswordForm(request.POST)
            if form_pwd.is_valid():
                data = form_pwd.cleaned_data
                if user.check_password(data['former_pwd']):
                    if data['confirm_pwd'] == data['new_pwd']:
                        user.set_password(data['new_pwd'])
                        user.save()
                        return redirect('/')
                    else : 
                        message = "new password and its confirmation do not match"
                        # display error message 'new password and its confirmation do not match'
                else : 
                    message = "Password could not be validated, if it is forgotten, please reset this one "
                    # Password could not be validated, if you forget , reset this one 
    form = UpdateUserForm({"username":user.username, "email":user.email})
    form_pwd = PasswordForm()
    return render(request,'core/settings.html',{'user':user,'form':form,'form_pwd':form_pwd,"message":message})

@login_required
def delete_account(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        return redirect("/")
    return render(request,'core/delete.html')

def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, username=data['username'], password=data['password'])
            if user != None:
                user.last_login = datetime.now()
                user.save()
                login(request,user=user)
                return redirect("/")   

    return render(request,'core/login.html',{'form':LoginForm})

slovo/core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
School Project Website
No commercial use 
{% endblock %}

slovo/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="{% static 'core/images/icon_2.png' %}">
        <link  href="{% static 'core/styles.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        <title>{% block title %}{% endblock %}  Sƚovo </title>

    </head>
    <body class="">
        <nav class="border-b flex justify-between px-3 py-3">
            <div class="flex justify-between  ">
                <a href="/" class=" font-semibold">
                    <img src="{% static 'core/images/logo.png' %}" alt="Logo" class="object-scale-down w-28 rounded-xl">
                </a>
            </div>
            <div class="relative">
                <a href="/" class=" vertical-center  text-red-600 anton-regular text-6xl"> Sƚovo </a>
            </div>
            <div class=" flex justify-end">
                <div class=" space-x-2 grid place-content-center">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'translation:profil' %}" class="text-center w-1/4 py-3 text-lg font-semibold hover:text-gray-500 "> Profil </a>
                    <a href="{% url 'core:settings' %}" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Ustawienia</a>
                    <a href="{% url 'core:logout' %}" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Wyloguj</a>
                    {% else %}
                    <a href="{% url 'core:signup' %}" class=" px-6 py-4 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"> Rejestracji</a>
                    <a href="{% url 'core:login' %}" class=" text-center px-6 py-4 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Zalogować się </a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="py-6 px-6 flex justify-between bg-gray-800 ">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400"> About </h3>

                <p class="text-lg text-gray-500">The EFLU (European Federation for Language Understanding ) owns this website. 
                    This is a fictionnal organization created to match the requirements of the RNCP : AI developer. The site was developed by 
                    the CP9 (Cipher Poland 9). @Copyright 2024 MIT Licence </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400"> Menu </h3>
                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-gray-500 hover:text-grey-300">About</a></li>
                    <li><a href="{% url 'core:contact' %}"  class="text-lg text-gray-500 hover:text-grey-300">Contact</a></li>
                    <li><a href="{% url 'core:privacy' %}"  class="text-lg text-gray-500 hover:text-grey-300">Privacy</a></li>
                    <li><a href="{% url 'core:terms_of_use' %}"  class="text-lg text-gray-500 hover:text-grey-300">Terms of use</a></li>
                </ul>
            </div>

        </footer>
    </body>
    {% block extra_body %}
    {% endblock %}
</html>

slovo/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block content %}
    If you encounter any bugs, or have any legal inquiries: <br>
    Please Contact Administrator at the following email : <br>
    
{% endblock %}

slovo/core/templates/core/delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Delete {% endblock %}
{% block content %}
    <form action="{% url 'core:delete'%}" method="post" class="border-amber-300 border-2 rounded-xl  p-6 mu-6 mx-auto bg-gray-100 rounded-xl ml-10 p-10  items-center">
        Are you sure you want to delete your account ?
        {% csrf_token %}
        <input name="delete" type="submit" class=" mt-6 py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white mr-10" value="Delete">
    </form>
{% endblock %}

slovo/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="px-6 py-6 min-h-screen flex flex-col items-center ">  
    <div class="p-6 flex flex-col items-center">
        <a href="{% url 'translation:translate' %}" class="mt-10 w-5/6">
            <img src="{% static 'core/images/main_img.jpg'%}" alt="" class="rounded-xl h-5/6" title="Poznań">
        </a>
    </div>          
</div>
{% endblock %}

slovo/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Login {% endblock %}
{% block content %}
<div class="px-6 py-6 min-h-screen flex flex-col items-center ">
    <div class="flex  justify-between">
        <a href="#" class="mt-10 w-1/2 ml-6">
            <img src="{% static 'core/images/wolin.jpg'%}" alt="" class="rounded-xl " title="wolin park">
        </a>
        <div class="w-1/2 p-6 mu-6 mx-auto bg-gray-100 rounded-xl mt-10 ml-10 ">
            <div class="flex justify-center">
                <h1 class="mb-6 text-3xl"> Login </h1>
            </div>
            <form method="post" action="." >
                {% csrf_token %}
                    <div class="mb-3">
                        <label class="inline-block mb-2"> Rzekomy </label> <br>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label class="inline-block mb-2 mb-2"> Hasło </label><br>
                        {{ form.password }}
                    </div>

                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {%for field in form %}
                                {{ field.errors}}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'core:signup' %}" class="underline text-lg text-slate-400 mt-2 "> Nie masz konta? Rejestr </a>
                    </div>
                    <div>
                        <a href="#" class="underline text-lg text-slate-400 mt-2 "> Zapomniałeś hasła ? </a>
                    </div>
                    <button class="py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white mt-5 w-1/5"> Login  </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

slovo/core/templates/core/privacy.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Privacy{% endblock %}
{% block content %}
Privacy :  
{% endblock %}

slovo/core/templates/core/settings.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} ustawienia {% endblock %}
{% block content %}
    {% if message %}
    <p class=" server-error rounded-xl  p-6 mu-6 mx-auto ">&#128531; {{ message}} </p>
    {% endif %}
    <form action="{% url 'core:settings'%}" method="post" class="border-amber-300 border-2 rounded-xl  p-6 mu-6 mx-auto bg-gray-100 rounded-xl ml-10 p-10  items-center">
        {% csrf_token %}
        {{form }}
        <div class="w-1/2 flex justify-end ">
            <input name="email_username" type="submit" class=" mt-6 py-4 px-8 text-lg bg-lime-500 bg-lime-700 rounded-xl text-white mr-10" value="Składać"> 
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-amber-100 rounded-xl">
            {%for field in form %}
                {{ field.errors}}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
    </form>
    
    <form action="{% url 'core:settings'%}" method="post" class="border-amber-300 border-2 rounded-xl  p-6 mu-6 mx-auto bg-gray-100 rounded-xl ml-10 p-10  items-center">
        {% csrf_token %}
        {{ form_pwd}}
        {% if form_pwd.errors or form_pwd.non_field_errors %}
        <div class="mb-3 p-6 bg-amber-100 rounded-xl">
            {%for field in form %}
                {{ field.errors}}
            {% endfor %}
            {{ form_pwd.non_field_errors }}
        </div>
        {% endif %}
        <div class="w-1/2 flex justify-end ">
            <input name="password" type="submit" class=" mt-6 py-4 px-8 text-lg bg-lime-500 bg-lime-700 rounded-xl text-white mr-10" value="Składać"> 
        </div>
    </form>
    <div>
        <a href="{% url 'core:delete' %}" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"> &#x1F5D1;&#xFE0F; Delete Account &#x1F5D1;&#xFE0F; </a>
    </div>
{% endblock %}

slovo/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<div class="px-6 py-6 min-h-screen flex flex-col items-center ">
    <div class="flex justify-between">
        <div class="w-1/2 p-6 mu-6 bg-gray-100 rounded-xl mt-10">
            <div>
                <h1 class=" text-center mb-6 text-3xl "> Sign Up</h1>
            </div>
            <form method="post" action="." >
                {% csrf_token %}
                    <div class="mb-3">
                        <label class="inline-block mb-2">  Rzekomy </label> <br>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label class="inline-block mb-2"> Email </label><br>
                        {{ form.email }}
                    </div>
                    <div class="mb-3">
                        <label class="inline-block mb-2 mb-2"> Hasło </label><br>
                        {{ form.password1 }}
                    </div>
                    <div class="mb-3">
                        <label class="inline-block mb-2 mb-2"> Powtórz Hasło </label><br>
                        {{ form.password2 }}
                    </div>

                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {%for field in form %}
                                {{ field.errors}}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                <div class="flex justify-center mt-5">
                    <button class="py-4 px-8 text-lg bg-red-500 hover:bg-red-700 rounded-xl text-white w-full font-semibold"> Submit </button>
                </div>
            </form>
        </div>
        <a href="#" class="mt-10 w-1/2 ml-6">
            <img src="{% static 'core/images/malbrok.jpg'%}" alt="" class="rounded-xl " title="Białowieża">
        </a>
    </div>
</div>
{% endblock %}

slovo/core/templates/core/terms_of_use.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Terms of Use{% endblock %}
{% block content %}
<h5>Images utilisées</h5>
<a href="#">Logo</a>
<a href="https://www.freepik.com/author/frdmn-project">Icône de frdmn</a> 
<a href="https://www.pologne.travel/fr-be/villes/poznan-capitale-de-la-grande-pologne">Poznan : Boris Stroujko - Fotolia </a>
<a href="https://templiers.org/malbork.html">Malbrok Castle</a>
<a href="https://www.pologne.travel/fr/quoi-visiter/nature/parcs-nationaux/parc-national-de-wolin">Wolin</a>
<a href="https://fr.wikipedia.org/wiki/For%C3%AAt_de_Bia%C5%82owie%C5%BCa">Bialowieza :  CC BY-SA 3.0 pl WildberryPassion </a>
{% endblock %}